### ISSUE TITLE
EGD Driver

### ISSUE THREAD

**Issue by lylyuanliang** [PTCInc/Kepware-ConfigAPI-SDK-Python#32]
Hello, since this is my first time working with Kepserver, there might be something I haven't handled correctly. When I run egd_test.py, it shows the message "Skipped: EGD Driver is not installed." Could you please guide me on how to install this EGD Driver?

**Comment by rlabbeptc** [comment]
Sorry for the delay. This is a sign that that Kepware server that you are connecting to does not have the EGD driver installed as part of hte installation.

Rerun the installer and make sure that the GE Ethernet Global Data driver is installed.

Let me know if you need anything else.
